### ISSUE TITLE
是否可以使用`require.context()`来监听文件夹？

### ISSUE THREAD

**Issue by cevio** [zfang1995/webpack-plugin-inverted-index-generator#1]
看了下源码，就是自动遍历文件夹，通过固定规则读取。我自己写了个[loader](https://github.com/woxjs/loader/blob/master/lib/helper.js#L68)，也是自动读文件夹。是不是可以考虑webpack提供的`require.context()`来做呢？毕竟我们自己监听是有成本的。

仅个人愚见！望交流！

**Comment by zfang1995** [comment]
> 看了下源码，就是自动遍历文件夹，通过固定规则读取。我自己写了个[loader](https://github.com/woxjs/loader/blob/master/lib/helper.js#L68)，也是自动读文件夹。是不是可以考虑webpack提供的`require.context()`来做呢？毕竟我们自己监听是有成本的。
> 
> 仅个人愚见！望交流！

谢谢大佬给出建议！
其实我对webpack有很多不了解的地方，它的很多API我都不清楚有什么用，比如这个 require.contex() 我都是第一次认识。
不过我会仔细思考你给的建议的。希望以后多交流。

**Comment by cevio** [comment]
你也在研究这个东西，我找到了动态注入的方法[webpack-inject-plugin](https://www.npmjs.com/package/webpack-inject-plugin)，这个的原理比较简单，就是在`compiler.options.entry`中添加一个`./inject.js?id=xxx!`这样一个url，注意后面的`!`表示在服务端返回内容。但是遇到一个问题就是如何在`webpack-dev-server`中动态替换，我找了很多方法都没有实现，甚至我给那个作者发送邮件（还没回复）。我希望我们可以交流下，联系方式你发我邮件吧 evio@vip.qq.com 一起探索下。
